# Generated by Django 5.2.8 on 2025-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
